name: read-the-docs

channels:
  - conda-forge
  - defaults
# Cannot do without defaults because of libgfortran.
# https://github.com/conda-forge/libgfortran-feedstock/issues/9

dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - sphinx
  - numpydoc
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
