dist: trusty  # need glibc >= 2.17 for pyqt5
sudo: false

language: python
cache: pip  # cache wheels for faster tests (PySide build can timeout)
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - xvfb

install:
  - pip install -U pip
  - pip install -U -r requirements.txt
  - pip install .

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
# - make lint
  - coverage run --branch --source pygsp setup.py test
  - make doc

after_success:
  - coveralls
