# Configuration file for automatic testing at travis-ci.org

dist: trusty  # need glibc >= 2.17 for pyqt5
sudo: false

language: python
cache: pip  # cache wheels for faster tests (PySide build can timeout)
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - xvfb

install:
  - pip install -U pip
  - pip install -U -r requirements.txt
  - python setup.py install

script:
# - make lint
  - xvfb-run make test
  - make doc

after_success:
  - coveralls
