# Configuration file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
#  - "pypy" fails to install numpy

addons:
  apt:
    packages:
    - python-dev
    - liblapack-dev
    - libatlas-dev
    - gcc
    - gfortran
    - libatlas-base-dev
    - python-matplotlib

before_install:
    - pip install -U pip
    - echo 'backend : Agg' > ~/.config/matplotlib/matplotlibrc

install:
    - python setup.py install

script: python setup.py test
