# Configuration file for automatic testing at travis-ci.org

language: python

dist: trusty  # need glibc >= 2.17 for pyqt5
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - xvfb

before_install:
  - pip install -U pip
  - pip install -U -r requirements.txt

install:
  - python setup.py install

script:
  - xvfb-run python setup.py test
