# Configuration file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "pypy" fails to install numpy

before_install:
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - if [[ $TRAVIS_PYTHON_VERSION -le '3' ]]; then echo installing matplotlib for python2; sudo apt-get install -qq  python-matplotlib; fi
    - if [[ $TRAVIS_PYTHON_VERSION -ge '3' ]]; then echo installing matplotlib for python3; pip install matplotlib; fi

install:
    # Backport of new unittest features for Python 2.6.
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    # Usage dependencies expressed in the package.
    - python setup.py install

script: python setup.py test
